---
- name: Make an Active Directory domai
  hosts: hosts
  tasks:

  - name: Create new Windows domain in a new forest with specific parameters
    ansible.windows.win_domain:
      database_path: C:\Windows\NTDS
      dns_domain_name: winnet.local
      domain_mode: WinThreshold
      domain_netbios_name: WINNET
      forest_mode: WinThreshold
      safe_mode_password: password123!
      sysvol_path: C:\Windows\SYSVOL
    register: domain_install
  - name: Reboot
    ansible.windows.win_reboot:
    when: domain_install.reboot_required
