---
dhcp_servers:
  - ip: 10.0.3.104
    name: central.winnet.local

dhcp_scopes:
  - name: winnet
    scope: 10.0.3.0
    server: central.winnet.local
    start: 10.0.3.240
    end: 10.0.3.245
    dns_server: 127.0.0.1
    default_gateway: 10.0.3.254
    netmask: 255.255.255.0

  - name: linnet
    scope: 10.0.4.0
    server: central.winnet.local
    start: 10.0.4.240
    end: 10.0.4.245
    dns_server: 10.0.4.104
    default_gateway: 10.0.4.254
    netmask: 255.255.255.0