---
domains:
  - name: winnet.local
    dadmins:
    - name: poguser
      password: P0gword
      firstname: Pog
      surname: User
    dusers:
    - name: normie
      password: P0gword
      firstname: Normal
      surname: User
  - name: linnet.local
    dadmins:
    - name: archbtw
      password: P0gword
      firstname: Arch
      surname: User
    dusers:
    - name: uwuntu
      password: P0gword
      firstname: Noob
      surname: User