all:
  hosts:
    pfsense:
      ansible_host: 10.0.4.1
      ansible_connection: ssh
      ansible_user: admin
      ansible_password: pfsense
  children:
    winnet:
      hosts:
        domain_controller_ssh:
          ansible_host: 10.0.3.2
          ansible_user: Administrator
          ansible_ssh_pass: P0gword
          ansible_connection: ssh
          ansible_shell_type: cmd
        domain_controller:
          ansible_host: 10.0.3.2
          ansible_user: Administrator
          ansible_password: P0gword
          ansible_connection: psrp
          ansible_psrp_cert_validation: ignore
          ansible_psrp_protocol: https
          ansible_psrp_auth: ntlm
          ansible_psrp_credssp_auth_mechanism: ntlm
          ansible_become_method: runas
          hostname: central #DO NOT INCLUDE THE DOMAIN NAME
      vars:
        domain_name: winnet.local
    linnet:
      hosts:
        ipa_server:
          ansible_host: 10.0.4.2
          ansible_user: root
          ansible_password: morbin
          ipaserver_domain: linnet.local
          ipaserver_realm: LINNET.LOCAL
          ipaserver_setup_dns: yes
          ipaserver_auto_forwarders: yes
          ipaadmin_password: P0gword1
          ipadm_password: P0gword1
        apex:
          ansible_host: 10.0.4.10
          ansible_user: root
          ansible_password: morbin
        monitoring:
          ansible_host: 192.168.1.7
          ansible_user: root
          ansible_password: morbin
