---
- name: Make AD Users
  hosts: domain_controller
  tasks:

  
  - name: Ensure Domain Admin is created and use custom credentials to create the user
    community.windows.win_domain_user:
      name: poguser
      firstname: Pog
      surname: User
      password: P0gword
      state: present
      groups:
        - Domain Admins
  - name: Ensure Domain Admin exists
    community.windows.win_domain_user:
      name: poguser
      state: query
  
  
  - name: Ensure User is created and use custom credentials to create the user
    community.windows.win_domain_user:
      name: normie
      firstname: Normal
      surname: User
      password: P0gword
      state: present
  - name: Ensure User exists
    community.windows.win_domain_user:
      name: normie
      state: query
  
