---
    - name: Set a hostname
      ansible.builtin.hostname:
        name: apex.linnet.local

    - name: Download epel-release
      ansible.builtin.dnf:
        name: epel-release == 9
        state: installed

    - name: Ensure git is at the latest version
      ansible.builtin.dnf:
        name: git >= 2.31.1
        state: installed

    - name: Ensure nginx is at the latest version
      ansible.builtin.dnf:
        name: nginx >= 1.20.1
        state: installed

    - name: Ensure openssl is at the latest version
      ansible.builtin.dnf:
        name: openssl >= 3.0.1
        state: installed

    - name: Ensure python's crypto is at the latest version
      ansible.builtin.dnf:
        name: python3-cryptography >= 36.0.1
        state: installed

    - name: Read-write git checkout from git
      ansible.builtin.git:
        repo: https://github.com/ryan77627/rochesterapex-com.git
        dest: /usr/share/nginx/apex

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/pki/nginx
        state: directory
        mode: '0755'

    - name: Generate an OpenSSL private key with a different algorithm (DSA)
      community.crypto.openssl_privatekey:
        path: /etc/pki/nginx/priv.key
        type: ECC
        curve: secp384r1

    - name: Create simple self-signed certificate
      community.crypto.x509_certificate:
        path: /etc/pki/nginx/server.crt
        privatekey_path: /etc/pki/nginx/priv.key
        provider: selfsigned

    - name: Copy "nginx.conf"
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
        backup: true

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
    
    - name: permit traffic in public zone for https service
      ansible.posix.firewalld:
        service: https
        zone: public
        immediate: yes
        permanent: yes
        state: enabled