---
- name: Get Comic Sans
  hosts: domain_controller
  tasks:

  - name: Send Powershell files to Remote
    ansible.builtin.fetch:
      src: C:\Windows\Fonts\comic.ttf
      dest: /home/morb/code/NSSA-320/apex/comic/comic.ttf
      flat: true
  - name: Send Powershell files to Remote
    ansible.builtin.fetch:
      src: C:\Windows\Fonts\comici.ttf
      dest: /home/morb/code/NSSA-320/apex/comic/comici.ttf
      flat: true
  - name: Send Powershell files to Remote
    ansible.builtin.fetch:
      src: C:\Windows\Fonts\comicbd.ttf
      dest: /home/morb/code/NSSA-320/apex/comic/comicbd.ttf
      flat: true
  - name: Send Powershell files to Remote
    ansible.builtin.fetch:
      src: C:\Windows\Fonts\comicz.ttf
      dest: /home/morb/code/NSSA-320/apex/comic/comicz.ttf
      flat: true