---
- name: Get Comic Sans
  hosts: ipa_server
  tasks:
  
  - name: update crypto policies
    ansible.builtin.command: update-crypto-policies --set DEFAULT:SHA1

  - name: import RPM key
    ansible.builtin.rpm_key:
      state: present
      key: https://packages.elastic.co/GPG-KEY-elasticsearch

  - name: Send Repo files to Remote
    ansible.builtin.copy:
      dest: /etc/yum.repos.d/
      src: /home/morb/code/NSSA-320/elastic/elastic.repo
  
  - name: Ensure filebeat is at the latest version
    ansible.builtin.dnf:
      name: filebeat == 8.5.2
      state: installed
  
  - name: Ensure metricbeat is at the latest version
    ansible.builtin.dnf:
      name: metricbeat == 8.5.2
      state: installed