---
- name: Make an Active Directory domai
  hosts: hosts
  tasks:
  
  - name: Change the hostname to sample-hostname
    ansible.windows.win_hostname:
      name: central
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
