---
- name: Rename Host
  hosts: domain_controller
  tasks:

  - name: Change the hostname to inventory-specified
    ansible.windows.win_hostname:
      name: "{{ hostname }}"
    register: res

  - name: Reboot
    ansible.windows.win_reboot:
    when: res.reboot_required
